name: SonarQube Scan

on:
  push:
    branches:
      - main  # Update with your branch name

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Update with your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Clear SonarScanner Cache
        run: |
          rm -rf /opt/sonar-scanner/.sonar/cache
        continue-on-error: true  # Continue even if the cache doesn't exist

      - name: SonarScanner Analysis
        run: |
          sonar-scanner -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set your SonarQube token here

      - name: Upload SonarQube Analysis Results
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: your-organization  # Update with your SonarCloud organization key
          token: ${{ secrets.SONAR_TOKEN }}  # Set your SonarCloud token here
