name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker pull sonarqube:lts-community
        docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube:lts-community
        sleep 1
      # You might need to adjust the sleep duration based on your SonarQube startup time

    - name: Install unzip
      run: |
        docker exec -u root sonarqube /bin/sh -c "apt-get update && apt-get install -y unzip"
      # Install unzip with elevated privileges

    - name: Download SonarScanner
      run: |
        docker exec -u root sonarqube /bin/sh -c "wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip"
      # Download the SonarScanner

    - name: Unzip SonarScanner
      run: |
        docker exec -u root sonarqube /bin/sh -c " /opt/sonar-scanner-cli-4.7.1.4182-linux.zip"
      # Unzip the downloaded file

    - name: Run SonarQube analysis
      run: |
        docker exec -u root sonarqube /bin/sh -c "/sonar-scanner-4.7.1.4182-linux/bin/sonar-scanner -Dsonar.host.url=http://192.168.3.17:9000 -Dsonar.login=sqp_42ed2dbd626b85f0af07e33970abbcd5dcb21833"
      # Replace <SONAR_LOGIN_TOKEN> with your SonarQube login token and adjust the version as needed

    - name: Stop and remove SonarQube container
      run: docker stop sonarqube
