name: Access Private Resource

on:
  push:
    branches:
      - main

jobs:
  access-private-resource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          export PRIVATE_API_KEY=$PRIVATE_API_KEY  # Set this secret in your GitHub repository
          export PRIVATE_API_URL=https://private-api.example.com  # Replace with your private resource URL

      - name: Access Private Resource
        run: |
          # You can access the private resource with the environment variables
          curl -H "Authorization: Bearer $PRIVATE_API_KEY" $PRIVATE_API_URL
